# Add configuration values here
  FACEBOOK_KEY: "491136411063102"
  FACEBOOK_SECRET: "02ca29c33c8fea9f7151683ad5743274"
  GOOGLE_KEY: "607620882992-l55qmpgmf1vjo5e9tj5i678pjph9gfmp.apps.googleusercontent.com"
  GOOGLE_SECRET: "0GFF4ImPKxivSdlitkX9O7Lo"
  GITHUB_KEY: "efdaa531214c4fac04a0"
  GITHUB_SECRET: "ae112098a1af3fc377694abc877732106b82bfbd"
  TWITTER_KEY: "edpJtQl2UGYcuYQOP4XVfh4x9"
  TWITTER_SECRET: "sxMwoGVlqbPofuuCeWOsRMTczfoAtEz3lIC866l2MIfpC3Jzh7"
  LINKEDIN_KEY: "75p26owkfk9xin"
  LINKEDIN_SECRET: "BRrJanVe3CAbpvZC"
  INSTAGRAM_KEY: "6b8c149ac82d4885a74be5f877206e56"
  INSTAGRAM_SECRET: "708b62d4e80a40ab884c521ed8627d27"

  MODULE_IDENTITY_API_HOST_URL: "http://api.qa1.nbos.in"
  MODULE_IDENTITY_API_CLIENT_KEY: "sample-app-client"
  MODULE_IDENTITY_API_CLIENT_SECRET: "sample-app-secret"



