# Add configuration values here
  API_HOST_URL: 'http://localhost:8080'
  API_CLIENT_KEY: 'vijaym-api-client'
  #API_CLIENT_SECRET: '$2a$10$R.b4bFfMN1a.fRptqpF.yelctUYOrVtqGnjSc4J8A1bhO03Qyz3Aa' 
  API_CLIENT_SECRET: 'vijaym-api-secret'
  FACEBOOK_KEY: "491136411063102"
  FACEBOOK_SECRET: "02ca29c33c8fea9f7151683ad5743274"
  GOOGLE_KEY: "607620882992-l55qmpgmf1vjo5e9tj5i678pjph9gfmp.apps.googleusercontent.com"
  GOOGLE_SECRET: "0GFF4ImPKxivSdlitkX9O7Lo"
  GITHUB_KEY: "efdaa531214c4fac04a0"
  GITHUB_SECRET: "ae112098a1af3fc377694abc877732106b82bfbd"
  TWITTER_KEY: "edpJtQl2UGYcuYQOP4XVfh4x9"
  TWITTER_SECRET: "sxMwoGVlqbPofuuCeWOsRMTczfoAtEz3lIC866l2MIfpC3Jzh7"
  LINKEDIN_KEY: "75p26owkfk9xin"
  LINKEDIN_SECRET: "BRrJanVe3CAbpvZC"
  INSTAGRAM_KEY: "6b8c149ac82d4885a74be5f877206e56"
  INSTAGRAM_SECRET: "708b62d4e80a40ab884c521ed8627d27"
  #INSTAGRAM_KEY: "7f16c33f88bc429a81995498241cd1c8"
  #INSTAGRAM_SECRET: "d5d43dc4a1834616874ca39ed3c0e5be"

production:
  API_HOST_URL: 'http://api.qa1.wavelabs.in/starter-app-rest-grails'
  API_CLIENT_KEY: 'my-client'
  API_CLIENT_SECRET: '$2a$10$R.b4bFfMN1a.fRptqpF.yelctUYOrVtqGnjSc4J8A1bhO03Qyz3Aa' 
  FACEBOOK_KEY: "491136411063102"
  FACEBOOK_SECRET: "02ca29c33c8fea9f7151683ad5743274"
  GOOGLE_KEY: "607620882992-l55qmpgmf1vjo5e9tj5i678pjph9gfmp.apps.googleusercontent.com"
  GOOGLE_SECRET: "0GFF4ImPKxivSdlitkX9O7Lo"
  GITHUB_KEY: "efdaa531214c4fac04a0"
  GITHUB_SECRET: "ae112098a1af3fc377694abc877732106b82bfbd"
  TWITTER_KEY: "edpJtQl2UGYcuYQOP4XVfh4x9"
  TWITTER_SECRET: "sxMwoGVlqbPofuuCeWOsRMTczfoAtEz3lIC866l2MIfpC3Jzh7"
  LINKEDIN_KEY: "75p26owkfk9xin"
  LINKEDIN_SECRET: "BRrJanVe3CAbpvZC"
  INSTAGRAM_KEY: "7f16c33f88bc429a81995498241cd1c8"
  INSTAGRAM_SECRET: "d5d43dc4a1834616874ca39ed3c0e5be"  


